#!/bin/bash

ASH3DROOT="../../.."
WRKDIR="${ASH3DROOT}/src"
ASH3D="${ASH3DROOT}/bin/Ash3d_TC"
#ASH3D="${ASH3DROOT}/bin/Ash3d_TC_debug"
TESTCASE=1
export TESTCASE
ASH3DCFL=0.99
export ASH3DCFL

# Subcases
sub=(0 1 2 3 4 5 6 7 8)
# Horizontal advection:
#  subcase 1 : x+y0
#  subcase 2 : x-y0
#  subcase 3 : x0y+
#  subcase 4 : x0y-
#  subcase 5 : x+y+
#  subcase 6 : x-y-
#  subcase 7 : x-y+
#  subcase 8 : x+y-

# Current limiter options
#      LIM_NONE,LIM_SUPERBEE,LIM_LAXWEN,LIM_BW,LIN_FROMM,LIM_MINMOD,LIM_MC
nlim=(LIM_NONE LIM_SUPERBEE LIM_LAXWEN LIM_BW LIM_FROMM LIM_MINMOD LIM_MC)
nlim_label=(LIM_NO LIM_SB LIM_LW LIM_BW LIM_FM LIM_MM LIM_MC)
#nlim=(LIM_SUPERBEE)
#nlim_label=(LIM_SB)
dx=(2000 1000 0500 0250 0125)
idx=3    # Approximate duration (minutes) for 7 and 2 limiters, respectively
         #  1 :  16 : 4
         #  2 :  17 ; 4.5
         #  3 :  29 ; 7.5
         #  4 : 130 ; 32
         #  5 : 

limmin=0 # index of above list starting with 0
limmax=1
submin=1 # note the that index 0 is a dummy slot
submax=8

echo "$idx" > TC1_LL_idx.dat
echo "$limmin $limmax" > TC1_LL_lim.dat
echo "$submin $submax" > TC1_LL_sub.dat

echo "*********************************************************"
echo "Running finite-volume cases (DCU)"
echo "*********************************************************"

mkdir -p DATA
for (( is=$submin;is<=$submax;is++))
do
 for (( il=$limmin;il<=$limmax;il++))
 do
  pushd ${WRKDIR}
  SUBCASE=${sub[is]}
  export SUBCASE
  LIMITER=${nlim[il]}
  export LIMITER
  echo $SUBCASE $LIMITER
  make -f makefile_optmod clean
  make -f makefile_optmod
  popd
  for (( k=0;k<idx;k++))
  do
   echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
   echo $k ' of ' ${idx}
   echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
   ${ASH3D} TC${TESTCASE}_LL_${dx[k]}.inp
   status=$?
   if [ $status -ne 0 ]; then
      echo "ERROR with job ${is}/${il}/${k} : ${SUBCASE} ${LIMITER} ${dx[k]} with code=$status"
      exit
    else
      mv TC${TESTCASE}_LL_Sub${SUBCASE}_St1_err.dat DATA/TC${TESTCASE}_LL_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St1_err.dat
      mv TC${TESTCASE}_LL_Sub${SUBCASE}_St2_err.dat DATA/TC${TESTCASE}_LL_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St2_err.dat
      mv TC${TESTCASE}_LL_Sub${SUBCASE}_St1_sol.dat DATA/TC${TESTCASE}_LL_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St1_sol.dat
      mv TC${TESTCASE}_LL_Sub${SUBCASE}_St2_sol.dat DATA/TC${TESTCASE}_LL_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St2_sol.dat
      rm 3d_tephra_fall*dat
   fi
   echo "-------------------------------------------------------------------------"
   echo "-------------------------------------------------------------------------"
   echo "-------------------------------------------------------------------------"
  done
 done
done
