#!/bin/bash

ASH3DROOT="../../.."
WRKDIR="${ASH3DROOT}/src"
ASH3D="${ASH3DROOT}/bin/Ash3d_TC_debug"
TESTCASE=1
export TESTCASE
sub=(0 1 2 3 4 5 6 7 8)
# Horizontal advection:
#  subcase 1 : x+y0
#  subcase 2 : x-y0
#  subcase 3 : x0y+
#  subcase 4 : x0y-
#  subcase 5 : x+y+
#  subcase 6 : x-y-
#  subcase 7 : x-y+
#  subcase 8 : x+y-

# Current limiter options
#      LIM_NONE,LIM_LAXWEN,LIM_BW,LIN_FROMM,LIM_MINMOD,LIM_SUPERBEE,LIM_MC

nlim=(LIM_SUPERBEE)
nlim_label=(LIM_SB)
dx=(2000 1000 0500 0250 0125)
inlim=1  # 4
idx=3    # 4

submin=1
submax=8

echo "*********************************************************"
echo "Running finite-volume cases (DCU)"
echo "*********************************************************"

for (( is=$submin;is<=$submax;is++))
do
 pushd ${WRKDIR}
 SUBCASE=${sub[is]}
 export SUBCASE
 echo $SUBCASE
 make clean
 make
 popd
 for (( k=0;k<idx;k++))
 do
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo $k ' of ' ${idx}
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  ${ASH3D} TC${TESTCASE}_LL_${dx[k]}.inp
  mv TC${TESTCASE}_LL_Sub${SUBCASE}_St1_err.dat DATA/TC${TESTCASE}_LL_Sub${SUBCASE}_${dx[k]}_St1_err.dat
  mv TC${TESTCASE}_LL_Sub${SUBCASE}_St2_err.dat DATA/TC${TESTCASE}_LL_Sub${SUBCASE}_${dx[k]}_St2_err.dat
  rm 3d_tephra_fall*dat
  echo "-------------------------------------------------------------------------"
  echo "-------------------------------------------------------------------------"
  echo "-------------------------------------------------------------------------"
 done
done
