#!/bin/bash

ASH3DROOT="../../.."
WRKDIR="${ASH3DROOT}/src"
ASH3D="${ASH3DROOT}/bin/Ash3d_TC"
#ASH3D="${ASH3DROOT}/bin/Ash3d_TC_debug"
TESTCASE=1
export TESTCASE

# Current limiter options
#      LIM_NONE,LIM_LAXWEN,LIM_BW,LIN_FROMM,LIM_MINMOD,LIM_SUPERBEE,LIM_MC
nlim=(LIM_NONE LIM_LAXWEN LIM_BW LIM_FROMM LIM_MINMOD LIM_SUPERBEE LIM_MC)
nlim_label=(LIM_NO LIM_LW LIM_BW LIM_FM LIM_MM LIM_SB LIM_MC)

dx=(50000 25000 12500 06250 03125)
idx=3    # 5

limmin=0 # index of above list starting with 0
limmax=7

echo "*********************************************************"
echo "Running finite-volume cases (DCU)"
echo "*********************************************************"

mkdir -p DATA_xy

for (( il=$limmin;il<=$limmax;il++))
do
 pushd ${WRKDIR}
 LIMITER=${nlim[il]}
 export LIMITER
 make -f makefile_optmod clean
 make -f makefile_optmod
 popd
 for (( k=0;k<idx;k++))
 do
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo $il ' of ' ${limmas} ' , ' $k ' of ' ${idx}
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  ${ASH3D} TC${TESTCASE}_${dx[k]}.inp
  mv TC${TESTCASE}_err.dat DATA_xy/TC${TESTCASE}_XY_${nlim_label[il]}_${dx[k]}_err.dat
  mv TC${TESTCASE}_sol.dat DATA_xy/TC${TESTCASE}_XY_${nlim_label[il]}_${dx[k]}_sol.dat
  grep Execution Ash3d.lst | grep -v CPU | cut -c 35-48 >> DATA_xy/TC${TESTCASE}_XY_${nlim_label[il]}_etime.dat
  echo "-------------------------------------------------------------------------"
  echo "-------------------------------------------------------------------------"
  echo "-------------------------------------------------------------------------"
 done
done
