#!/bin/bash

ASH3DROOT="../../.."
WRKDIR="${ASH3DROOT}/src"
ASH3D="${ASH3DROOT}/bin/Ash3d_TC"
#ASH3D="${ASH3DROOT}/bin/Ash3d_TC_debug"
TESTCASE=3
export TESTCASE
ASH3DCFL=0.99
export ASH3DCFL

# Subcases
#  Only one case: Rigid rotation of block and cone concentration

# Current limiter options
#      LIM_NONE,LIM_SUPERBEE,LIM_LAXWEN,LIM_BW,LIN_FROMM,LIM_MINMOD,LIM_MC
nlim=(LIM_NONE LIM_SUPERBEE LIM_LAXWEN LIM_BW LIM_FROMM LIM_MINMOD LIM_MC)
nlim_label=(LIM_NO LIM_SB LIM_LW LIM_BW LIM_FM LIM_MM LIM_MC)
dx=(50000 25000 12500 06250 03125)
idx=3    # Approximate duration (minutes) for 7 and 2 limiters, respectively
         #  1 :     :  
         #  2 :     : 
         #  3 :     : 2m21
         #  4 :     : 
         #  5 : 

limmin=0 # index of above list starting with 0
limmax=6

echo "$idx" > TC3_XY_idx.dat
echo "$limmin $limmax" > TC3_XY_lim.dat

echo "*********************************************************"
echo "Running finite-volume cases (DCU)"
echo "*********************************************************"

mkdir -p DATA
for (( il=$limmin;il<=$limmax;il++))
do
 pushd ${WRKDIR}
 LIMITER=${nlim[il]}
 export LIMITER
 echo $LIMITER
 make -f makefile_optmod clean
 make -f makefile_optmod
 popd
 for (( k=0;k<idx;k++))
 do
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo $il ' of ' ${limmas} ' , ' $k ' of ' ${idx}
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  ${ASH3D} TC${TESTCASE}_XY_${dx[k]}.inp
  status=$?
  if [ $status -ne 0 ]; then
     echo "ERROR with job ${is}/${il}/${k} : ${SUBCASE} ${LIMITER} ${dx[k]} with code=$status"
     exit
   else
     mv TC${TESTCASE}_err.dat DATA/TC${TESTCASE}_XY_${nlim_label[il]}_${dx[k]}_err.dat
     mv TC${TESTCASE}_sol.dat DATA/TC${TESTCASE}_XY_${nlim_label[il]}_${dx[k]}_sol.dat
     grep Execution Ash3d.lst | grep -v CPU | cut -c 35-48 >> DATA/TC${TESTCASE}_XY_${nlim_label[il]}_etime.dat
  fi
  echo "-------------------------------------------------------------------------"
  echo "-------------------------------------------------------------------------"
  echo "-------------------------------------------------------------------------"
 done
done
