#!/bin/bash

# We want to be able to set the number of limiters and number of dx levels globally
# through environment levels for easy scripting.  Two limiters (None, and SuperBee) and
# three dx levels is the default for quick execution.  These can be changed by
# uncommenting the section below.
#
#  Check for limiter number passed as environment variable on command-line:
if [ -z ${limmax+x} ]; then echo "Setting limmax to 1"; limmax=1; else echo "limmax is set to '$limmax'"; fi

#  Check for idx passed as environment variable on command-line:
if [ -z ${idx+x} ]; then echo "Setting idx to 3"; idx=3; else echo "idx is set to '$idx'"; fi
# Approximate duration (minutes) for 7 and 2 limiters, respectively
#  1 :     :
#  2 :     :
#  3 :     :
#  4 :     :
#  5 :     :

#  Uncomment here if you want to over-ride these values
# idx=1
# limmax=4

ASH3DROOT="../../.."
WRKDIR="${ASH3DROOT}/src"
ASH3D="${ASH3DROOT}/bin/Ash3d_TC"
TESTCASE=2
export TESTCASE
ASH3DCFL=0.99
export ASH3DCFL

# Subcases
sub=(0 1 2 3 4)
# Vertical advection:
#  subcase 1 : Wind blows up (no fall velocity)
#  subcase 2 : Wind blows down (no fall velocity)
#  subcase 3 : No z wind (fall velocity +)
#  subcase 4 : No z wind (fall velocity -)

# Current limiter options
#      LIM_NONE,LIM_SUPERBEE,LIM_LAXWEN,LIM_BW,LIN_FROMM,LIM_MINMOD,LIM_MC
nlim=(LIM_NONE LIM_SUPERBEE LIM_LAXWEN LIM_BW LIM_FROMM LIM_MINMOD LIM_MC)
nlim_label=(LIM_NO LIM_SB LIM_LW LIM_BW LIM_FM LIM_MM LIM_MC)
dx=(50000 25000 12500 06250 03125)

limmin=0 # index of above list starting with 0
submin=1
submax=4

echo "$idx" > TC${TESTCASE}_XY_idx.dat
echo "$limmin $limmax" > TC${TESTCASE}_XY_lim.dat
echo "$submin $submax" > TC${TESTCASE}_XY_sub.dat

echo "*********************************************************"
echo "Running finite-volume cases (DCU)"
echo "*********************************************************"

mkdir -p DATA PLOTS
for (( is=$submin;is<=$submax;is++))
do
 for (( il=$limmin;il<=$limmax;il++))
 do
  pushd ${WRKDIR}
  SUBCASE=${sub[is]}
  export SUBCASE
  LIMITER=${nlim[il]}
  export LIMITER
  echo $SUBCASE $LIMITER
  make -f makefile_optmod clean
  make -f makefile_optmod
  popd
  for (( k=0;k<idx;k++))
  do
   echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
   echo $k ' of ' ${idx}
   echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
   if [ "${is}" -eq "1" ] ; then
     ${ASH3D} TC${TESTCASE}_${dx[k]}.inp
   elif [ "${is}" -eq "2" ] ; then
     ${ASH3D} TC${TESTCASE}_${dx[k]}.inp
   elif [ "${is}" -eq "3" ] ; then
     ${ASH3D} TC${TESTCASE}_S3_${dx[k]}.inp
   elif [ "${is}" -eq "4" ] ; then
     ${ASH3D} TC${TESTCASE}_S4_${dx[k]}.inp
   fi
   status=$?
   if [ $status -ne 0 ]; then
      echo "ERROR with job ${is}/${il}/${k} : ${SUBCASE} ${LIMITER} ${dx[k]} with code=$status"
      exit
    else
      mv TC${TESTCASE}_Sub${SUBCASE}_St1_err.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St1_err.dat
      mv TC${TESTCASE}_Sub${SUBCASE}_St2_err.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St2_err.dat
      mv TC${TESTCASE}_Sub${SUBCASE}_St1_sol.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St1_sol.dat
      mv TC${TESTCASE}_Sub${SUBCASE}_St2_sol.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St2_sol.dat
      grep Execution Ash3d.lst | grep -v CPU | cut -c 35-48 >> DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_etime.dat
      rm 3d_tephra_fall*dat
   fi
   echo "-------------------------------------------------------------------------"
   echo "-------------------------------------------------------------------------"
   echo "-------------------------------------------------------------------------"
  done
 done
done
