#!/bin/bash

# We want to be able to set the number of limiters and number of dx levels globally
# through environment levels for easy scripting.  Two limiters (None, and SuperBee) and
# three dx levels is the default for quick execution.  These can be changed by
# uncommenting the section below.
#
#  Check for limiter number passed as environment variable on command-line:
if [ -z ${limmax+x} ]; then echo "Setting limmax to 1"; limmax=1; else echo "limmax is set to '$limmax'"; fi

#  Check for idx passed as environment variable on command-line:
if [ -z ${idx+x} ]; then echo "Setting idx to 3"; idx=3; else echo "idx is set to '$idx'"; fi
# Approximate duration (minutes) for 7 and 2 limiters, respectively
#  1 :     :
#  2 :     :
#  3 :     :
#  4 :     :
#  5 :     :

#  Uncomment here if you want to over-ride these values
# idx=1
# limmax=4

ASH3DROOT="../../.."
WRKDIR="${ASH3DROOT}/src"
ASH3D="${ASH3DROOT}/bin/Ash3d"
TESTCASE=6
export TESTCASE
ASH3DCFL=0.80
export ASH3DCFL
GRID=XY
# Subcases
#  Only one case: Method of Manufactured Solution

# Current limiter options
#      LIM_NONE,LIM_SUPERBEE,LIM_LAXWEN,LIM_BW,LIN_FROMM,LIM_MINMOD,LIM_MC
nlim=(LIM_NONE LIM_SUPERBEE LIM_LAXWEN LIM_BW LIM_FROMM LIM_MINMOD LIM_MC)
nlim_label=(LIM_NO LIM_SB LIM_LW LIM_BW LIM_FM LIM_MM LIM_MC)
dx=(200000 100000 050000 025000 012500)

limmin=0 # index of above list starting with 0

echo "$idx" > TC${TESTCASE}_${GRID}_idx.dat
echo "$limmin $limmax" > TC${TESTCASE}_${GRID}_lim.dat

echo "*********************************************************"
echo "Running finite-volume cases (DCU)"
echo "*********************************************************"

mkdir -p DATA PLOTS
for (( il=$limmin;il<=$limmax;il++))
do
 pushd ${WRKDIR}
 SUBCASE=0
 export SUBCASE
 LIMITER=${nlim[il]}
 export LIMITER
 echo $SUBCASE $LIMITER

 make -f makefile_optmod clean
 make -f makefile_optmod
 popd
 cp ${ASH3D} ${ASH3D}_TC${TESTCASE}${SUBCASE}_${nlim_label[il]}
 for (( k=0;k<idx;k++))
  do
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo $il ' of ' ${limmax} ' , ' $k ' of ' ${idx}
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "${ASH3D} TC${TESTCASE}_${GRID}_${dx[k]}.inp"
   ${ASH3D} TC${TESTCASE}_${GRID}_${dx[k]}.inp
  status=$?
  if [ $status -ne 0 ]; then
     echo "ERROR with job ${is}/${il}/${k} : ${SUBCASE} ${LIMITER} ${dx[k]} with code=$status"
     exit
   else
   echo "Backing up output files"
     mv TC${TESTCASE}_err.dat DATA/TC${TESTCASE}_${GRID}_${nlim_label[il]}_${dx[k]}_err.dat
     if [ $k -eq 0 ]; then
       rm -f DATA/TC${TESTCASE}_${GRID}_${nlim_label[il]}_etime.dat
     fi
     grep solver Ash3d.lst | cut -c 35-48 >> DATA/TC${TESTCASE}_${GRID}_${nlim_label[il]}_etime.dat
     rm -f 3d_tephra_fall.nc Ash3d.lst progress.txt
  fi
  echo "-------------------------------------------------------------------------"
  echo "-------------------------------------------------------------------------"
  echo "-------------------------------------------------------------------------"
 done
done
